### ISSUE TITLE
how do i build miniaudio for macos?

### ISSUE THREAD

**Issue by JonnycatMeow** [doggy-dentures/3dsenpai#1]
i have a mac please tell me how to do it or research it please

**Comment by doggy-dentures** [comment]
If you're unfamiliar with linking native external libraries in Haxe, don't bother. MiniAudio isn't necessary and I only included it for a niche feature. You can replace the "music" and "vocals" variables in PlayState.hx with a FlxSound object instead of the existing AudioStreamThing object, eliminating the need for MiniAudio at all. I think one of the mobile port forks for this repo did that already.
